### ISSUE TITLE
compare to org-roam?

### ISSUE THREAD

**Issue by titaniumbones** [Kinneyzhang/gkroam.el#15]
Are you able to briefly explain compare to org-roam and explain why a person might prefer one or the other? Thank you so much!

**Comment by Kinneyzhang** [comment]
Gkroam use 'ripgrep' to calculate linked references and put backlinks at the bottom of page page buffer at real time while org-roam cache them in database and show them in a side window.  Gkroam can hide and show brackets automatically, just like Roam Research (when ```gkroam-dynamic-brackets-mode``` is turned on). Gkroam can capture or edit many pages in one capture window and save them all separately (use ```gkroam-capture``` ), just like Roam Research sidebar, etc.

Well, I'm not a deep user of org-roam, so I cannot tell you more about the difference. Actually, I don't care about something about org-roam, I have been developing my roam replica on top of emacs org-mode and have not referred to org-roam. That's it.
