### ISSUE TITLE
[Proposal] Change the way to supply initial/default value to completing-read (not using INITIAL-INPUT)

### ISSUE THREAD

**Issue by zbelial** [Kinneyzhang/gkroam.el#17]
First of all, this is not a serious problem.  

The reasons why I proposal this change are:
1. Using `INITIAL-INPUT` to insert a value is deprecated now and the recommended way is to use `DEF` to supply a default value.   And
2. I'm using `selectrum`, which ignores `INITIAL-INPUT` because of reason 1 above, so when I call `gkroam-daily`, there is no initial value in the minibuffer. 

I can make a PR if you agree to make the change.

**Comment by Kinneyzhang** [comment]
Thanks, free feel to make a PR.
